services:
  mysql:
    build: ./mysql
    container_name: fm-mysql
    restart: always
    ports:
      - "6034:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=your-mysql-root-password
      - MYSQL_DATABASE=fantasy_music
      - MYSQL_USER=your-database-user
      - MYSQL_PASSWORD=your-database-password
      - TZ=Asia/Shanghai
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fm-network

  redis:
    image: redis:latest
    container_name: fm-redis
    restart: always
    ports:
      - "6035:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass Lb147258369*
    networks:
      - fm-network

  backend:
    build: ./service
    container_name: fm-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_MAIL_HOST=smtp.qq.com # 这里替换成你的smtp提供商地址
      - SPRING_MAIL_PORT=465  # 兜底防止配置文件不生效
      - SPRING_MAIL_PROTOCOL=smtps
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=false
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED=false
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SOCKETFACTORY_PORT=465
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SOCKETFACTORY_CLASS=javax.net.ssl.SSLSocketFactory
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SOCKETFACTORY_FALLBACK=false
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - fm-network

  frontend:
    build: ./nginx
    container_name: fm-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fm-network

volumes:
  mysql_data:

networks:
  fm-network:
    driver: bridge
